[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]

[[bin]]
name = "day4"
path = "src/day4/main.rs"

[[bin]]
name = "day5"
path = "src/day5/main.rs"

[[bin]]
name = "day7"
path = "src/day7/main.rs"